# Checks that we can build and validate the Unittest
name: Pull-Request-Checks

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: 3.9

      - name: Install Poetry Action
        uses: snok/install-poetry@v1.3.3
      
      - name: Cache Poetry virtualenv
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-$
          restore-keys: |
            poetry-$

      - name: Install Dependencies using Poetry
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'
    
      - name: Run pytest
        run: poetry run python -m pytest -v --cov=./ tests/
    
      - name: Run Coverage
        run: poetry run python -m coverage report -m;
    
      - name: Generate XML Report
        run: poetry run python -m coverage xml
